### ISSUE TITLE
[v3.0] Unable to build project

### ISSUE THREAD

**Issue by AaronSadlerUK** [leekelleher/umbraco-contentment#175]
### Which Contentment version are you using?

3.0.0

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

9.0.1

### Bug summary

Unable to build project after upgrading from the beta to 3.0.0 stable

### Steps to reproduce

Upgrade from 3.0.0-beta001 to 3.0.0 stable

### Expected result / actual result

Expected the project to build, instead I get the following errors:

```
error CS0246: The type or namespace name 'ContentBlockPreviewView' could not be found (are you missing a using directive or an assembly reference?)
error CS0115: 'App_Plugins_Contentment_render_ContentBlockPreview.ExecuteAsync()': no suitable method found to override
```

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.
